version: 2
updates:
  # === GitHub Actions ===
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    target-branch: "main"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    groups:
      symfony:
        patterns:
          - "symfony/*"
      laravel:
        patterns:
          - "laravel/*"
      php-tools:
        patterns:
          - "phpunit/*"
          - "psr/*"
          - "guzzlehttp/*"
          - "monolog/*"
      other-php:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    target-branch: "main"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    groups:
      react:
        patterns:
          - "react*"
          - "@types/react*"
      testing:
        patterns:
          - "vitest"
          - "jest"
          - "@testing-library/*"
      build:
        patterns:
          - "vite"
          - "webpack*"
          - "rollup*"
          - "esbuild*"
      ui:
        patterns:
          - "@mui/*"
          - "tailwind*"
          - "shadcn*"
      other-js:
        patterns:
          - "*"
