version: "2"
plugins:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      ignore_warnings: true
      standard: "./phpcs.xml"
  sonar-php:
    enabled: true
    tests:
      - tests/**
  phpmd:
    enabled: true
    config:
      file_extensions:
        - php
exclude_patterns:
- "tests/"
- "spec/"
- "**/vendor/"
- "database/migrations"
