version: "2"
plugins:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      ignore_warnings: true
      standard: "./phpcs.xml"
  sonar-php:
    enabled: true
#    checks:
#      php:S1192:
#        enabled: false
    tests:
      - tests/**
  phpmd:
    enabled: true
    config:
      file_extensions:
        - php
    checks:
      CleanCode/StaticAccess:
        enabled: false
exclude_patterns:
- "./database/migrations/"
- "tests/"
- "spec/"
- "**/vendor/"
