FROM ubuntu:24.04

WORKDIR /app

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Moscow
ENV PATH=node_modules/.bin:$PATH
ENV PHP_VERSION=8.4
ENV NODE_MAJOR=24

RUN apt-get update \
    && apt-get -y install software-properties-common \
    && add-apt-repository ppa:ondrej/php \
    && apt-get install -y \
    make \
    curl \
    gnupg \
    git \
    libpq-dev \
    libzip-dev \
    sqlite3 \
    unzip \
    zip \
    racket

RUN raco pkg install sicp

RUN apt-get install -y \
    php${PHP_VERSION} \
    php${PHP_VERSION}-bcmath \
    php${PHP_VERSION}-exif \
    php${PHP_VERSION}-pdo \
    php${PHP_VERSION}-pgsql \
    php${PHP_VERSION}-pgsql \
    php${PHP_VERSION}-zip \
    php${PHP_VERSION}-xdebug \
    php${PHP_VERSION}-dom \
    php${PHP_VERSION}-xml \
    php${PHP_VERSION}-mbstring \
    php${PHP_VERSION}-sqlite3 \
    php${PHP_VERSION}-curl

RUN curl -sL https://deb.nodesource.com/setup_${NODE_MAJOR}.x | bash -
RUN apt-get install -y nodejs

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
COPY ./xdebug.ini /etc/php/${PHP_VERSION}/conf.d/docker-php-ext-xdebug.ini

ENV PATH=/app/node_modules/.bin/:${PATH}
