# syntax = edrevo/dockerfile-plus

INCLUDE+ Dockerfile

COPY . .

RUN composer install

RUN php artisan config:cache
RUN php artisan route:cache
RUN npm ci
RUN npm run prod

RUN php artisan migrate:fresh --force --seed

CMD [ "php artisan serve --host 0.0.0.0 --port 8000" ]
