@extends('layouts.app')

@section('title')
    {{ 'How to Study Structure and Interpretation of Computer Programs (SICP)' }}
@endsection
@section('description')
    {{ 'A guide on how to read one of the main reference books on computer science for any developer — SICP' }}
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mx-auto">
                <h1>How to Study Structure and Interpretation of Computer Programs (SICP)</h1>
                <p class="lead">Why and how to study one of the most important books in computer science</p>

                <img
                        src="{{ asset('images/sicp_cover.jpg') }}"
                        alt="SICP Book Cover"
                        width="60%"
                        height="60%"
                        class="img-fluid mb-4"
                >

                <p><strong>SICP is both a book and a legendary course at MIT (Massachusetts Institute of Technology).</strong></p>

                <p>SICP is not a book about programming languages or software development, not about OOP, functional programming, or design patterns.</p>

                <p>SICP is a book about computer science. It is about perceiving computers as abstract machines used for manipulating data. Despite the fact that the book was first published in 1979, it has not lost its relevance and will not lose it in the future. SICP has consistently remained at the top of the best programming learning books for decades.</p>



                <blockquote class="blockquote">
                    <p>This is one of the great classics of computer science. I bought my first copy 15 years ago, and I still don't feel I have learned everything the book has to teach. <em>— Paul Graham</em>.</p>
                </blockquote>

                <p>Should you read it? Absolutely yes, for all developers, regardless of language or experience. SICP is a fairly difficult book, which is why this guide you are reading now exists.</p>

                <h2>Very short summary</h2>

                <h3>Abstraction with functions</h3>
                <ol>
                    <li>Elements of programs
                        <ul>
                            <li>Expressions</li>
                            <li>Evaluation strategies</li>
                            <li>Substitution model of evaluation</li>
                        </ul>
                    </li>
                    <li>Functions and processes generated by them
                        <ul>
                            <li>Linear recursion and iteration</li>
                            <li>Tree recursion</li>
                        </ul>
                    </li>
                    <li>Higher-order functions
                        <ul>
                            <li>Functions as arguments</li>
                            <li>Functions as generalizations</li>
                            <li>Functions as return values</li>
                        </ul>
                    </li>
                </ol>

                <h3>Abstraction with data</h3>
                <ol>
                    <li>Introduction to data abstraction
                        <ul>
                            <li>Abstraction barriers</li>
                            <li>What is data?</li>
                        </ul>
                    </li>
                    <li>Hierarchical data and the closure property
                        <ul>
                            <li>Representation of sequences</li>
                            <li>Hierarchical structures</li>
                            <li>Sequences as standard interfaces</li>
                        </ul>
                    </li>
                    <li>Symbolic data
                        <ul>
                            <li>Quotation</li>
                        </ul>
                    </li>
                    <li>Multiple representations of abstract data
                        <ul>
                            <li>Tagging data</li>
                            <li>Data-directed programming. Additivity.</li>
                        </ul>
                    </li>
                </ol>

                <h3>Modularity, Objects, and State</h3>
                <ol>
                    <li>Assignment and local state
                        <ul>
                            <li>Advantages of assignment</li>
                            <li>Disadvantages of assignment</li>
                        </ul>
                    </li>
                    <li>The environment model
                        <ul>
                            <li>Rules of evaluation</li>
                            <li>Application</li>
                            <li>Frames as repositories of local state</li>
                        </ul>
                    </li>
                    <li>Modeling with mutable data
                        <ul>
                            <li>Mutable list</li>
                            <li>Representation of a queue</li>
                            <li>Representation of tables</li>
                        </ul>
                    </li>
                    <li>Concurrency</li>
                    <li>Streams</li>
                </ol>

                <h3>Metalinguistic abstractions</h3>
                <p>...</p>

                <h3>Computation with register machines</h3>
                <p>...</p>

                <hr>

                <h2>Recommendations</h2>

                <p>The first thing to understand: SICP is not just a book. It is a university course written in book form. It is complex and extensive, and it is useless to go through it without practice. Luckily, you don't need to invent exercises. At the end of each chapter there are problem sets the authors ask you to solve. Some of them are purely mathematical (prove something), or require a strong math background. You can and should skip those, otherwise you may quickly lose motivation.</p>

                <h3>How much to read</h3>

                <p>SICP can be conditionally divided into two parts. The first part includes chapters 1, 2, and 3. The second — chapters 4 and 5. The difference is that the second part digs very deep, and only a truly passionate person can get through it. For this reason, Hexlet recommends setting a goal to complete the first three chapters. The rest can be safely postponed.</p>

                <h3>Language</h3>

                <p>The book uses Scheme as the language for examples and exercises, created by the authors of the course. It is one of the Lisp dialects. As is typical for Lisp languages, Scheme has a primitive syntax that can be learned in just a few hours. It looks unusual for those familiar only with mainstream languages, but it has serious advantages, which are discussed in the book.</p>

                <p>The choice of Scheme as the main language of the course is justified by the fact that Scheme allows focusing on the essence instead of syntax, showing pure concepts in their raw form. Like any Lisp, Scheme is incredibly expressive because in the language everything is an expression, and there are no statements at all.</p>

                <p>The second reason is homoiconicity — the property of languages where data and code are the same. This is hard to grasp in words; it must be experienced in practice. There is also a third reason — macros, but they are not used in the book.</p>

                <p>Scheme itself is primarily the standard plus different implementations of that standard. Currently, one of the most developed and still actively maintained descendants of Scheme is <a href="https://racket-lang.org/" target="_blank" referrerpolicy="no-referrer">Racket</a>. Hexlet recommends studying SICP specifically with Racket. For this guide, we prepared a <a href="https://github.com/hexlet-boilerplates/sicp-racket" target="_blank" referrerpolicy="no-referrer">repository</a> that you can use as a base for your code. It's worth checking it out at least to see how to configure Racket for compatibility with the exact Scheme standard used in the book's examples: very few implementations can recreate "that exact" environment, but Racket can! Don't forget to properly configure your editor: Lisp languages require editor support for comfortable work.</p>

                <h2>Practice</h2>

                <p>On GitHub you can <a href="https://github.com/search?q=sicp" target="_blank" referrerpolicy="no-referrer">find</a> many repositories with solutions to SICP problems in all sorts of programming languages. We strongly recommend doing the same: create a repository in your own account and upload all your solutions. Ideally, each solution should be accompanied by <a href="https://docs.racket-lang.org/rackunit/" target="_blank" referrerpolicy="no-referrer">tests</a>. This approach is great not only because you improve your Git skills and get extra motivation, but also because you build code that you can show when job hunting. Moreover, there's a good chance your interviewer will know about SICP. That will earn you karma points and give you a chance for a productive conversation.</p>

                <h2>Additional links</h2>

                <ul>
                    <li><a href="https://web.mit.edu/6.001/6.037/sicp.pdf" target="_blank" referrerpolicy="no-referrer">Structure and Interpretation of Computer Programs, 2nd ed.</a></li>
                    <li><a href="https://www.youtube.com/playlist?list=PLhMnuBfGeCDNgVzLPxF9o5UNKG1b-LFY9" target="_blank" referrerpolicy="no-referrer">Course: Structure and Interpretation of Computer Programs (UC Berkeley, 2010)</a></li>
                </ul>
            </div>
        </div>
    </div>
@endsection
