<?php

return [
    'title' => 'Exchange 11 cents',
    'description' => [
        '1' =>
        'Draw the tree illustrating the process generated by the ',
        '2' =>
        ' procedure of section 1.2.2 in making change for 11 cents. ' .
        'What are the orders of growth of the space and number of steps used by this process as the amount to be changed increases?',
    ],
];
