<?php

return [
    'title' => 'The sine of an angle',
    'description' => [
        '1' =>
        "The sine of an angle (specified in radians) can be computed by making use of the approximation ",
        '2' =>
        " if ",
        '3' =>
        " is sufficiently small, and the trigonometric identity",
        '4' =>
        "to reduce the size of the argument of ",
        '5' =>
        ". (For purposes of this exercise an angle is considered ''sufficiently small'' if its magnitude is not greater than 0.1 radians.) " .
        "These ideas are incorporated in the following procedures:",
        '6' =>
        "a.  How many times is the procedure ",
        '7' =>
        " applied when ",
        '8' =>
        " is evaluated?",
        '9' =>
        "b.  What is the order of growth in space and number of steps (as a function of ",
        '10' =>
        ") used by the process generated by the ",
        '11' =>
        " procedure when ",
        '12' =>
        " is evaluated?",
    ],
];
