<?php

return [
    'title' => 'Procedures of sum',
    'description' => [
        '1' =>
        "Each of the following two procedures defines a method for adding two positive integers in terms of the procedures ",
        '2' =>
        ", which increments its argument by 1, and ",
        '3' =>
        ", which decrements its argument by 1.",
        '4' =>
        "Using the substitution model, illustrate the process generated by each procedure in evaluating ",
        '5' =>
        ". Are these processes iterative or recursive?",
    ],
];
