<?php

return [
    'title' => 'Iterative or recursive',
    'description' => [
        '1' =>
        'Each of the following two procedures defines a method for adding two positive integers in terms of the procedures inc, ' .
        'which increments its argument by 1, and dec, which decrements its argument by 1.',
        '2' =>
        'Using the substitution model, illustrate the process generated by each procedure in evaluating (+ 4 5). ' .
        'Are these processes iterative or recursive?'
    ]
];
