<?php

return [
    'title' => "Algorithm as a procedure",
    'description' => [
        '1' =>
        " a. Implement this algorithm as a procedure ",
        '2' =>
        " that takes two term lists ",
        '3' =>
        " and ",
        '4' =>
        " as arguments and returns a list ",
        '5' =>
        ", ",
        '6' =>
        ", which are ",
        '7' =>
        " and ",
        '8' =>
        " reduced to lowest terms via the algorithm given above. Also write a procedure ",
        '9' =>
        ", analogous to ",
        '10' =>
        ", that checks to see if the two ",
        '11' =>
        " have the same variable. If so, ",
        '12' =>
        " strips off the variable and passes the problem to ",
        '13' =>
        ", then reattaches the variable to the two term lists supplied by ",
        '14' =>
        ".",
        '15' =>
        "b. Define a procedure analogous to ",
        '16' =>
        " that does what the original ",
        '17' =>
        " did for integers:",
        '18' =>
        "and define ",
        '19' =>
        " as a generic operation that calls ",
        '20' =>
        " to dispatch to either ",
        '21' =>
        " (for polynomial arguments) or ",
        '22' =>
        " (for ",
        '23' =>
        " arguments). You can now easily make the rational-arithmetic package reduce fractions to lowest terms by having ",
        '24' =>
        " call ",
        '25' =>
        " before combining the given numerator and denominator to form a rational number. " .
        "The system now handles rational expressions in either integers or polynomials. To test your program, try the example at the beginning of this extended exercise:",
        '26' =>
        "See if you get the correct answer, correctly reduced to lowest terms.",
        '27' =>
        "The GCD computation is at the heart of any system that does operations on rational functions. The algorithm used above, although mathematically straightforward, is extremely slow. " .
        "The slowness is due partly to the large number of division operations and partly to the enormous size of the intermediate coefficients generated by the pseudodivisions. " .
        "One of the active areas in the development of algebraic-manipulation systems is the design of better algorithms for computing polynomial GCDs.",
    ],
];
