<?php

return [
    'title' => 'Internal Definitions',
    'description' => [
        '1' =>
        'In section ',
        '2' =>
        ' we saw how the environment model described the behavior of procedures with local state. ' .
        'Now we have seen how internal definitions work. ' .
        'A typical message-passing procedure contains both of these aspects. ' .
        'Consider the bank account procedure of section ',
        '3' =>
        'Show the environment structure generated by the sequence of interactions',
        '4' =>
        'Where is the local state for ',
        '5' =>
        ' kept? Suppose we define another account',
        '6' =>
        'How are the local states for the two accounts kept distinct? ' .
        'Which parts of the environment structure are shared between ',
        '7' =>
        ' and ',
    ],
];
