<?php

return [
    'title' => 'Internal Definitions',
    'description1' =>
        'In section ',
    'description2' =>
        ' we saw how the environment model described the behavior of procedures with local state. ' .
        'Now we have seen how internal definitions work. ' .
        'A typical message-passing procedure contains both of these aspects. ' .
        'Consider the bank account procedure of section ',
    'description3' =>
        ':',
    'description4' =>
        'Show the environment structure generated by the sequence of interactions',
    'description5' =>
        'Where is the local state for ',
    'description6' =>
        ' kept? Suppose we define another account',
    'description7' =>
        'How are the local states for the two accounts kept distinct? ' .
        'Which parts of the environment structure are shared between ',
    'description8' =>
        ' and ',
    'description9' =>
        '?'
];
