<?php

return [
    'title' => "Solve-2nd procedure",
    'description' => [
        '1' =>
        "Figure 3.35:  Signal-flow diagram for the solution to a second-order linear differential equation.",
        '2' =>
        "Consider the problem of designing a signal-processing system to study the homogeneous second-order linear differential equation",
        '3' =>
        "The output stream, modeling ",
        '4' =>
        ", is generated by a network that contains a loop. This is because the value of ",
        '5' =>
        " depends upon the values of ",
        '6' =>
        " and ",
        '7' =>
        " and both of these are determined by integrating ",
        '8' =>
        ". The diagram we would like to encode is shown in figure 3.35. Write a procedure ",
        '9' =>
        " that takes as arguments the constants ",
        '10' =>
        ", ",
        '11' =>
        ", and ",
        '12' =>
        " and the initial values ",
        '13' =>
        " and ",
        '14' =>
        " for ",
        '15' =>
        " and ",
        '16' =>
        " and generates the stream of successive values of ",
        '17' =>
        ".",
    ],
];
